[project]
name = "wikiparse"
version = "0.1.0"
description = "Another WikiText/WikiCode/MediaWiki Parser"
authors = ["Kiruse"]
license = "MIT"
readme = "README.md"
python = "^3.8" # earlier versions not yet verified
homepage = "https://github.com/Kiruse/WikiParse.py"
repository = "https://github.com/Kiruse/WikiParse.py"
documentation = "https://github.com/Kiruse/WikiParse.py"

keywords = ["WikiText", "WikiCode", "MediaWiki", "Parser"]

[dependencies]
advlog = "^1"

[dev-dependencies]
build = "^0.8"
pytest = "^7.1.2"

[build-system]
requires = ["setuptools >= 42"]
build-backend = "setuptools.build_meta"
